### ISSUE TITLE
Distribute a pre-compiled GROMACS binary

### ISSUE THREAD

**Issue by bioinfkaustin** [bioinfkaustin/gromacs-on-colab#2]
Currently, the installation notebook compiles GROMACS from source code, because [only source code is distributed by the GROMACS project](https://manual.gromacs.org/2023.2/download.html). Because this toolkit runs only on Colab, it is reasonable for us to instead distribute our own pre-compiled GROMACS binary for Colab. This would be particularly helpful for free-tier Colab users, who may be subject to early disconnection during the slow compilation step, which can take several hours (#1).

**Comment by LiangGerui** [comment]
**Thank you for your response, it was really helpful.**
I made some minor changes to the four Jupyter notebooks you provided and ran them on AI Studio. The compilation process was significantly faster thanks to the multi-core CPU option provided by AI Studio. I will review the modified Jupyter notebook scripts one more time before releasing them. In the process of this release, I will adhere to the stipulations of the GNU Affero General Public License v3.0.

**Comment by bioinfkaustin** [comment]
@LiangYat-sen, thank you for planning to release your changes! It is much appreciated.

**Comment by bioinfkaustin** [comment]
Fixed in 0256875.
